server:
  port: 8082
  servlet:
    context-path: /**

spring:
  profiles:
    active: prod
  aop:
    auto: true

logging:
  config: classpath:logback-spring.xml
  file:
    path: /opt/log/umer-alihealth
  level:
    root: info

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml

token:
  # 密钥
  secret-key: 123kafkahiwhfakna0808234*)*)(
  # token 过期的秒数
  token-expire-second: 60
#  4800

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS