spring:
  datasource:
    url: jdbc:mysql://192.168.44.128:3306/healthact?useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver