server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthact?useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  config-location: classpath:/mybatis-config.xml